AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for creating a CloudFront distribution for a custom domain.

Parameters:
  environment:
    Type: String
    AllowedValues:
      - prod
      - dev
  service:
    Type: String
    Default: 'www.1md3md.com'
    AllowedValues:
      - www.1md3nd.com

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${environment}-${service}-s3Bucket"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  cloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt s3Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:120569601292:certificate/5d5ad968-7ef3-4ed2-bb98-4ef2422cc0ef"
          SslSupportMethod: sni-only
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref s3Bucket
                - /*
            Principal: 
              Service: 'cloudfront.amazonaws.com'
            Condition:
              StringLike:
                'AWS:SourceArn': !Join
                  - ''
                  - - 'arn:aws:cloudfront::120569601292:distribution/'
                    - !Ref cloudFrontDistribution

Outputs:
  CloudFrontDomain:
    Description: The CloudFront distribution domain name.
    Value: !GetAtt cloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${environment}-${service}-cdn"

  BucketName:
    Value: !Ref s3Bucket
    Description: Name of the sample Amazon S3 bucket with a logging configuration.
    Export:
      Name: !Sub "${environment}-${service}-s3Bucket"
