service: apis-for-projects

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: location.lambda_handler
    events:
      - httpApi:
          path: /location
          method: post

resources:
  Resources:
    locationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: locationTable
        AttributeDefinitions:
          - AttributeName: session_id
            AttributeType: S
          - AttributeName: city
            AttributeType: S
          - AttributeName: country_code
            AttributeType: S
          - AttributeName: country_name
            AttributeType: S
          - AttributeName: postal
            AttributeType: S
          - AttributeName: latitude
            AttributeType: N
          - AttributeName: longitude
            AttributeType: N
          - AttributeName: IPv4
            AttributeType: S
          - AttributeName: state
            AttributeType: S
        KeySchema:
          - AttributeName: session_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
