service: apis-for-projects

provider:
  name: aws
  runtime: python3.10
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:us-east-1:*:table/dev-location-dynamodb

functions:
  hello:
    handler: location.lambda_handler
    events:
      - httpApi:
          path: /location
          method: POST
      - httpApi:
          path: /location
          method: GET

plugins:
  - serverless-python-requirements
