name: Build and Deploy React App with CloudFront

on:
  push:
    branches:
      - main
      - dev
    paths:
      - Frontend/**
      - .github/workflows/frontend-build.yaml

env:
  AWS_REGION: "us-east-1"
  BUCKET_NAME: ${{ github.ref == 'refs/heads/main' && 'test-1md3nd-cloudfront-s3-bucket-1' || 'dev-www.1md3nd.com-s3bucket' }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ github.ref == 'refs/heads/main' && 'EGLB0491BG8I7' || 'E1BNHR8A1WWMBI' }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Build
        run: |
          cd Frontend/Portfolio
          npm install
          npm run build
        env:
          REACT_APP_BRANCH: ${{ github.ref_name }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/OIDC-GitHub-Role
          role-session-name: github-actions-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          cd Frontend/Portfolio
          aws s3 sync ./build s3://${{ env.BUCKET_NAME }} --delete
          aws s3 cp ./src/Assets/portfolio-image.jpg s3://${{ env.BUCKET_NAME }}/assets/

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Deployment Complete
        run: echo "🎉 React app has been successfully deployed and CloudFront cache invalidated!"