name: Build and Deploy React App with CloudFront

on:
  push:
    branches:
      - main
    paths:
      - Frontend/**
      - .github/workflows/frontend-build.yaml

env:
  BUCKET_NAME: "test-1md3nd-cloudfront-s3-bucket-1"
  AWS_REGION: "us-east-1"
  CLOUDFRONT_DISTRIBUTION_ID: "EGLB0491BG8I7"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies and build the React app
      - name: Install Dependencies and Build
        run: |
          cd Frontend/Portfolio
          npm install
          npm run build

      # Configure AWS credentials using GitHub OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::120569601292:role/OIDC-GitHub-Role
          role-session-name: github-actions-session
          aws-region: ${{ env.AWS_REGION }}

      # Upload the build files to S3
      - name: Deploy to S3
        run: |
          cd Frontend/Portfolio
          aws s3 sync ./build s3://${{ env.BUCKET_NAME }} --delete

      # Invalidate CloudFront cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      # Output success message
      - name: Deployment Complete
        run: echo "🎉 React app has been successfully deployed and CloudFront cache invalidated!"
