
name: Compile LaTeX
on:
  push:
    branch:
      - main
    paths:
      - Public/resume/latex/**
      - .github/workflows/latex-resume-build.yaml
  workflow_dispatch:

jobs:
  latex-build:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build using latexmk
        run: latexmk -pdf -output-directory=Public/resume/out Public/resume/latex/default.tex

      - name: List
        run: ls Public/resume/out

      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: Public/resume/out/default.pdf
          
  upload-resume:
    needs: latex-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-pdf
          
      - name: List
        run: |
          ls
          mv ./default.pdf ./Public/resume/out/default.pdf
        
      - name: Upload pdf to github
        uses: EndBug/add-and-commit@v9
        with:
          add: "Public/resume/out/default.pdf"
          message: "Upload latest resume pdf"
    