name: Compile and Upload LaTeX Resume

on:
  push:
    branches:
      - main
    paths:
      - Public/resume/latex/**
      - .github/workflows/latex-resume-build.yaml
  workflow_dispatch:

jobs:
  build-pdf:
    name: Build PDF with LaTeX
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Output Directory
        run: mkdir -p Public/resume/out

      - name: Compile LaTeX Resume
        run: |
          latexmk -pdf -output-directory=Public/resume/out Public/resume/latex/default.tex
          ls -lh Public/resume/out

      - name: Upload Compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: Public/resume/out/default.pdf

  upload-to-repo:
    name: Commit PDF to Repository
    needs: build-pdf
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download PDF Artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf

      - name: Ensure Output Directory
        run: mkdir -p Public/resume/out

      - name: Move PDF into Output Folder
        run: mv default.pdf Public/resume/out/default.pdf

      - name: Commit and Push PDF
        uses: EndBug/add-and-commit@v9
        with:
          add: Public/resume/out/default.pdf
          message: "Update compiled resume PDF"
          default_author: github_actions
