name: Compile LaTeX
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - Public/resume/latex/**

jobs:
  container:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build using latexmk
        run: latexmk -pdf -output-directory=Public/resume/out Public/resume/latex/default.tex

      - name: Upload document
        uses: EndBug/add-and-commit@v9
        with:
          add: Public/resume/out
          message: "Uploaded latest resume pdf"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"